### ISSUE TITLE
Can't run on web with --release or --profile

### ISSUE THREAD

**Issue by kiszewski** [Flutterando/auto_injector#14]
After runApp using ModularApp I got the error: 
"Expected symbol ":" but found "AutoInjectorImpl_addInstance_closure" at line 1 column 46."

When run as debug all works fine.

Flutter version: 3.13.1

Dependency versions:
auto_injector: 2.0.0+2
flutter_modular: 6.0.1+1
modular_core: 3.1.0

*I was able to caught this error only using sentry, there is no log or exception.

**Comment by kiszewski** [comment]
Stack trace: 
`ParserException: Expected symbol ":" but found "AutoInjectorImpl_addInstance_closure" at line 1 column 46.
  at Object.wrapException(main.dart.js:10067:43)
  at Parser._expectSymbol$1(main.dart.js:167563:17)
  at Object.Bind_Bind(main.dart.js:20880:14)
  at AutoInjectorImpl._auto_injector_base$_add$1$5$config$instance$key$type(main.dart.js:159140:16)
  at AutoInjectorImpl.addInstance$1$1(main.dart.js:158966:12)
  at _innerInjector_closure.call$1(main.dart.js:276005:9)
  at Object.AutoInjector_AutoInjector(main.dart.js:20763:12)
  at <fn>(main.dart.js:453127:68)
  at holder.<computed>(main.dart.js:130:21)
  at injector_closure.call$1(main.dart.js:276012:27)`

**Comment by joaovvrodrigues** [comment]
Same here 👍🏽

**Comment by jacobaraujo7** [comment]
Fiexed. Update auto_injector and flutter_modular
